# -*- coding: utf-8 -*-
"""Parser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PEMsW2tqU6gD5LHutzlFd24LSpa6O5PV
"""


import spacy

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/Custom_NER"

import streamlit as st

pip install transformers

pip install --upgrade transformers

pip install spacy_transformers

model = spacy.load("/content/drive/MyDrive/Custom_NER/output/model-best")

pip install pdfminer.six

from pdfminer.high_level import extract_text

def extract_text_from_pdf(pdf_path):
    return extract_text(pdf_path)

# Streamlit App
st.title("Resume Parser")

uploaded_file = st.file_uploader("Upload Resume", type=["pdf"])

if uploaded_file is not None:
    # Extract text from the uploaded PDF file
    resume_text = extract_text_from_pdf(uploaded_file)

    st.write("### Extracted Text")
    st.write(resume_text)

    # Parse the resume using the NER model
    parsed_info = parse_resume(resume_text)

    st.write("### Parsed Information")
    for entity, label in parsed_info:
        st.write(f"{label}: {entity}")

